[Configuration]
ServiceMode=1
TrayIconMode=2
StatusWindowMode=0
; COMPUTER_NAME_PLACEHOLDER
; EMAIL_FREQ_PLACEHOLDER

[Alerts]
EmailEnabled=1
; Cseréld le a sajátodra az e-Mail címet!
EmailTo=xxxxxxx@gmail.com
EmailAlertStatus=1
